build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

# publish:
#   docker:
#     username: auser
#     password: apassword
#     email: anemail
#     repo: plugins/hello
#     when:
#       branch: master

